version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile          # multi-stage file you just added
    container_name: backend-dev
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/devdb
      JWT_SECRET: dev-secret          # ← use any throw-away string for local dev
    ports:
      - "4000:4000"
    volumes:                          # live-reload: host code ↔ container
      - .:/app
      - /app/node_modules             # keep deps inside container
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
