name: Test Docker Hub login   # workflow title

on:
  push:
    branches: [main]          # runs on every push to main
  pull_request:               # …and on every PR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout code
      - uses: actions/checkout@v4

      # 2. log in to Docker Hub using repo secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. set up Buildx driver so cache works
      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      # 4. compute tags & OCI labels
      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/chrome-extension-backend
          # ---- tag strategy ----
          tags: |
            # add 'latest' only when building the default branch (main)
            type=raw,value=latest,enable={{is_default_branch}}
            # add 'pr-<number>' only on pull-request events
            type=raw,value=pr-{{pull_request_number}},enable={{is_pull_request}}
            # always add short commit-hash tag
            type=sha

      # 5. build image, push only on main
      - name: Build (push only on main)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
