name: Test Docker Hub login

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Buildx driver (enables cache-to/from)
      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Tags & labels
      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/chrome-extension-backend
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=pr-{{pull_request_number}},enable={{is_pull_request}}
            type=sha

      # Build image ― push only on main
      - name: Build (push only on main)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
