name: Scheduled Mongo ETL Export

on:
  # Run every Monday at 7 AM UTC and on manual trigger
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  export-etl:
    runs-on: ubuntu-latest
    steps:
      # 1. Get latest code from repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Inject MongoDB connection secret
      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env

      # 5. Run Python ETL script to export Mongo to Excel
      - name: Run ETL script
        run: python etl/report_etl.py

      # 6. Upload Excel report to AWS S3 bucket
      - name: Upload report.xlsx to S3
        run: |
          aws s3 cp report.xlsx s3://$S3_BUCKET_NAME/report.xlsx --acl private --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          
      # 7. Send notification email when upload succeeds
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.yahoo.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "ETL Report Uploaded: ${{ github.workflow }} Success"
          body: |
            ✅ The ETL pipeline completed and report.xlsx has been uploaded to S3.

            Repo: ${{ github.repository }}
            Workflow run: ${{ github.run_id }}
            Time: ${{ github.run_started_at }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          
      # 8. Post message to Slack on workflow success
      - name: Notify Slack channel
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ ETL pipeline finished! report.xlsx has been uploaded to S3 for repository: ${{ github.repository }} (run ${{ github.run_id }})"}' \
          $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
